package com.billbull.backend.sales.delivery;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.billbull.backend.inventory.warehouse.Warehouse;
import com.billbull.backend.sales.invoice.SalesInvoice;
import com.billbull.backend.settings.branch.Branch;

@Entity
@Table(name = "delivery_notes", indexes = {
		@Index(name = "idx_dn_linked_invoice", columnList = "sales_invoice_id"),
		@Index(name = "idx_dn_branch", columnList = "branch_id"),
		// Speeds the date-bounded sales-report loader.
		@Index(name = "idx_dn_date", columnList = "dn_date")
})
@jakarta.persistence.EntityListeners(com.billbull.backend.common.ownership.OwnershipAuditListener.class)
@org.hibernate.annotations.Filter(name = "ownerFilter", condition = "created_by_user_id = :ownerId")
public class DeliveryNote  implements com.billbull.backend.common.ownership.OwnedEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

    /** Stable owner id for ownership filtering; stamped on persist by OwnershipAuditListener. Nullable forever. */
    @jakarta.persistence.Column(name = "created_by_user_id", updatable = false)
    private Long createdByUserId;

	private String dnNumber;
	private LocalDate dnDate;

	private String customerCode;
	private String customerName;

	private String salesOrderNo;
	private String proformaNo;
	@Column(name = "branch_id")
	private Long branchId;
	private String branchName;
	private String branchCode;

	/** Navigable view of {@link #branchId}. Read-only — writes go through {@link #setBranchId(Long)}. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id", insertable = false, updatable = false)
	@com.fasterxml.jackson.annotation.JsonIgnore
	private Branch branchEntity;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "warehouse_id", nullable = false)
	private Warehouse warehouse;

	private String driverName;
	private String vehicleNo;
	private String trackingNo;

	@Column(length = 1000)
	private String shippingAddress;

	private Integer totalLines;
	private Integer totalQty;
	private Integer totalBoxes;

	@Enumerated(EnumType.STRING)
	private DeliveryNoteStatus status;

	private String receivedBy;
	private LocalDate receivedDate;

	private Boolean autoGenerated = false;
	private String sourceDocumentType; // e.g., "SALES_INVOICE"
	private Long sourceDocumentId;

	// Revenue and COGS recognized when this DN was marked DELIVERED.
	// Stored so cancellation can reverse the exact amounts.
	private java.math.BigDecimal recognizedRevenue;
	private java.math.BigDecimal recognizedCogs;

	// Set to true after GL journals are successfully posted for this DN.
	// Guards against duplicate accounting if markDelivered() is retried.
	// columnDefinition supplies the DEFAULT so ALTER TABLE succeeds on existing rows.
	@Column(columnDefinition = "boolean not null default false")
	private boolean financialPosted = false;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sales_invoice_id")
	private SalesInvoice linkedSalesInvoice;

	@OneToMany(mappedBy = "deliveryNote", cascade = CascadeType.ALL, orphanRemoval = true)
	private List<DeliveryNoteItem> items = new ArrayList<>();

	public Long getId() {
		return id;
	}

	// ... existing getters ...

	public String getReceivedBy() {
		return receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	public LocalDate getReceivedDate() {
		return receivedDate;
	}

	public void setReceivedDate(LocalDate receivedDate) {
		this.receivedDate = receivedDate;
	}

	public Boolean getAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(Boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

	public String getSourceDocumentType() {
		return sourceDocumentType;
	}

	public void setSourceDocumentType(String sourceDocumentType) {
		this.sourceDocumentType = sourceDocumentType;
	}

	public Long getSourceDocumentId() {
		return sourceDocumentId;
	}

	public void setSourceDocumentId(Long sourceDocumentId) {
		this.sourceDocumentId = sourceDocumentId;
	}

	public SalesInvoice getLinkedSalesInvoice() {
		return linkedSalesInvoice;
	}

	public void setLinkedSalesInvoice(SalesInvoice linkedSalesInvoice) {
		this.linkedSalesInvoice = linkedSalesInvoice;
	}

	public String getDnNumber() {
		return dnNumber;
	}

	public LocalDate getDnDate() {
		return dnDate;
	}

	public String getCustomerCode() {
		return customerCode;
	}

	public String getCustomerName() {
		return customerName;
	}

	public String getSalesOrderNo() {
		return salesOrderNo;
	}

	public String getProformaNo() {
		return proformaNo;
	}

	public Long getBranchId() {
		return branchId;
	}

	public void setBranchId(Long branchId) {
		this.branchId = branchId;
	}

	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getBranchCode() {
		return branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public Branch getBranchEntity() { return branchEntity; }

	public Warehouse getWarehouse() {
		return warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	public String getDriverName() {
		return driverName;
	}

	public String getVehicleNo() {
		return vehicleNo;
	}

	public String getTrackingNo() {
		return trackingNo;
	}

	public String getShippingAddress() {
		return shippingAddress;
	}

	public Integer getTotalLines() {
		return totalLines;
	}

	public Integer getTotalQty() {
		return totalQty;
	}

	public Integer getTotalBoxes() {
		return totalBoxes;
	}

	public DeliveryNoteStatus getStatus() {
		return status;
	}

	public List<DeliveryNoteItem> getItems() {
		return items;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setDnNumber(String dnNumber) {
		this.dnNumber = dnNumber;
	}

	public void setDnDate(LocalDate dnDate) {
		this.dnDate = dnDate;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public void setSalesOrderNo(String salesOrderNo) {
		this.salesOrderNo = salesOrderNo;
	}

	public void setProformaNo(String proformaNo) {
		this.proformaNo = proformaNo;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public void setTrackingNo(String trackingNo) {
		this.trackingNo = trackingNo;
	}

	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	public void setTotalLines(Integer totalLines) {
		this.totalLines = totalLines;
	}

	public void setTotalQty(Integer totalQty) {
		this.totalQty = totalQty;
	}

	public void setTotalBoxes(Integer totalBoxes) {
		this.totalBoxes = totalBoxes;
	}

	public void setStatus(DeliveryNoteStatus status) {
		this.status = status;
	}

	public void setItems(List<DeliveryNoteItem> items) {
		this.items = items;
	}

	public java.math.BigDecimal getRecognizedRevenue() {
		return recognizedRevenue;
	}

	public void setRecognizedRevenue(java.math.BigDecimal recognizedRevenue) {
		this.recognizedRevenue = recognizedRevenue;
	}

	public java.math.BigDecimal getRecognizedCogs() {
		return recognizedCogs;
	}

	public void setRecognizedCogs(java.math.BigDecimal recognizedCogs) {
		this.recognizedCogs = recognizedCogs;
	}

	public boolean isFinancialPosted() {
		return financialPosted;
	}

	public void setFinancialPosted(boolean financialPosted) {
		this.financialPosted = financialPosted;
	}

	// getters & setters

    @Override
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    @Override
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }
}
