package com.billbull.backend.sales.delivery;

import org.hibernate.Hibernate;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import com.billbull.backend.financials.generalledger.postingengine.PostingEngineService;
import com.billbull.backend.inventory.product.Product;
import com.billbull.backend.inventory.product.ProductBarcode;
import com.billbull.backend.inventory.product.ProductBarcodeRepository;
import com.billbull.backend.inventory.product.ProductRepository;
import com.billbull.backend.inventory.warehouse.Warehouse;
import com.billbull.backend.inventory.warehouse.WarehouseRepository;
import com.billbull.backend.inventory.warehouse.WarehouseStockService;
import com.billbull.backend.inventory.warehouse.BinRepository;
import com.billbull.backend.purchase.stockmovement.StockMovementRepository;
import com.billbull.backend.purchase.stockmovement.StockMovementService;
import com.billbull.backend.purchase.stockmovement.StockSourceType;
import com.billbull.backend.sales.invoice.SalesInvoice;
import com.billbull.backend.sales.invoice.SalesInvoiceItem;
import com.billbull.backend.sales.invoice.SalesInvoiceRepository;
import com.billbull.backend.sales.stockstrategy.StockDeductionStrategyService;
import com.billbull.backend.inventory.warehouse.Bin;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Service
@Transactional
public class DeliveryNoteService {

    private final DeliveryNoteRepository repo;
    private final WarehouseStockService warehouseStockService;
    private final ProductRepository productRepo;
    private final WarehouseRepository warehouseRepo;
    private final StockMovementService stockMovementService;
    private final StockMovementRepository stockMovementRepo;
    private final com.billbull.backend.sales.salesorder.SalesOrderService salesOrderService;
    private final BinRepository binRepo;
    private final StockDeductionStrategyService stockStrategy;
    private final PostingEngineService postingEngineService;
    private final SalesInvoiceRepository salesInvoiceRepo;
    private final ProductBarcodeRepository barcodeRepo;

    public DeliveryNoteService(
            DeliveryNoteRepository repo,
            WarehouseStockService warehouseStockService,
            ProductRepository productRepo,
            WarehouseRepository warehouseRepo,
            StockMovementService stockMovementService,
            StockMovementRepository stockMovementRepo,
            com.billbull.backend.sales.salesorder.SalesOrderService salesOrderService,
            BinRepository binRepo,
            StockDeductionStrategyService stockStrategy,
            PostingEngineService postingEngineService,
            SalesInvoiceRepository salesInvoiceRepo,
            ProductBarcodeRepository barcodeRepo) {
        this.repo = repo;
        this.warehouseStockService = warehouseStockService;
        this.productRepo = productRepo;
        this.warehouseRepo = warehouseRepo;
        this.stockMovementService = stockMovementService;
        this.stockMovementRepo = stockMovementRepo;
        this.salesOrderService = salesOrderService;
        this.binRepo = binRepo;
        this.stockStrategy = stockStrategy;
        this.postingEngineService = postingEngineService;
        this.salesInvoiceRepo = salesInvoiceRepo;
        this.barcodeRepo = barcodeRepo;
    }

    private DeliveryNoteResponse toResponse(DeliveryNote dn) {
        hydrateDeliveryItemDisplayData(dn);

        DeliveryNoteResponse r = new DeliveryNoteResponse();

        r.id = dn.getId();
        r.dnNumber = dn.getDnNumber();
        r.dnDate = dn.getDnDate();

        r.customerCode = dn.getCustomerCode();
        r.customerName = dn.getCustomerName();

        r.salesOrderNo = dn.getSalesOrderNo();
        r.proformaNo = dn.getProformaNo();

        // ✅ FIX: convert Warehouse entity → String
        r.warehouse = dn.getWarehouse() != null
                ? dn.getWarehouse().getName()
                : null;

        r.driverName = dn.getDriverName();
        r.vehicleNo = dn.getVehicleNo();
        r.trackingNo = dn.getTrackingNo();
        r.shippingAddress = dn.getShippingAddress();

        r.receivedBy = dn.getReceivedBy();
        r.receivedDate = dn.getReceivedDate();

        r.autoGenerated = dn.getAutoGenerated();
        r.sourceDocumentType = dn.getSourceDocumentType();
        r.sourceDocumentId = dn.getSourceDocumentId();
        r.linkedSalesInvoiceNumber = dn.getLinkedSalesInvoice() != null
                ? dn.getLinkedSalesInvoice().getInvoiceNumber()
                : null;

        // Auto-generated DNs from invoices are classified as "Picking" —
        // they represent warehouse pick instructions tied to the sale.
        // Manually linked (Before-Sale) DNs are classified as "Before Sale".
        r.type = (dn.getAutoGenerated() != null && dn.getAutoGenerated()
                && "SALES_INVOICE".equals(dn.getSourceDocumentType()))
                        ? "Picking"
                        : "Before Sale";

        r.totalLines = dn.getTotalLines();
        r.totalQty = dn.getTotalQty();
        r.totalBoxes = dn.getTotalBoxes();

        r.status = dn.getStatus();

        r.items = dn.getItems().stream().map(item -> {
            DeliveryNoteItemResponse ir = new DeliveryNoteItemResponse();
            ir.id = item.getId();
            ir.itemCode = item.getItemCode();
            ir.barcode = item.getBarcode();
            ir.description = item.getDescription();
            ir.unit = item.getUnit();
            ir.orderedQty = item.getOrderedQty();
            ir.image = item.getImage();
            ir.prevDeliveredQty = item.getPrevDeliveredQty();
            ir.foc = item.getFoc();
            ir.focUnit = item.getFocUnit();
            ir.remarks = item.getRemarks();
            ir.currentQty = item.getCurrentQty();
            ir.boxes = item.getBoxes();
            ir.binId = item.getBinId();
            ir.salesOrderItemId = item.getSalesOrderItemId();
            ir.price = item.getPrice();
            ir.disc = item.getDisc();
            ir.tax = item.getTax();
            ir.cost = item.getCost();
            return ir;
        }).toList();

        return r;
    }

    /* ================= CREATE / UPDATE ================= */

    public DeliveryNoteResponse create(DeliveryNoteRequest req) {
        DeliveryNote dn = new DeliveryNote();
        mapToEntity(req, dn);
        dn.setStatus(DeliveryNoteStatus.DRAFT);
        return toResponse(repo.save(dn));
    }

    public DeliveryNoteResponse update(Long id, DeliveryNoteRequest req) {
        DeliveryNote dn = getEntity(id);

        if (dn.getStatus() == DeliveryNoteStatus.DELIVERED) {
            throw new IllegalStateException("Delivered note is locked");
        }

        dn.getItems().clear();
        mapToEntity(req, dn);
        return toResponse(repo.save(dn));
    }

    /* ================= READ ================= */

    @Transactional(readOnly = true)
    public List<DeliveryNoteResponse> list() {
        return repo.findAll().stream().map(this::toResponse).toList();
    }

    @Transactional(readOnly = true)
    public DeliveryNoteResponse get(Long id) {
        return toResponse(getEntity(id));
    }

    @Transactional(readOnly = true)
    public List<DeliveryNoteResponse> getUninvoicedForCustomer(String customerCode) {
        // Exclude only CANCELLED so DRAFT, DISPATCHED, and DELIVERED all appear in
        // modal
        return repo.findUninvoicedByCustomer(customerCode, DeliveryNoteStatus.CANCELLED)
                .stream()
                .map(this::toResponse)
                .toList();
    }

    public void delete(Long id) {
        repo.deleteById(id);
    }

    /* ================= STATUS FLOW ================= */

    public DeliveryNoteResponse markDispatched(Long id) {

        DeliveryNote dn = getEntity(id);

        if (dn.getStatus() != DeliveryNoteStatus.DRAFT) {
            throw new IllegalStateException("Only Draft notes can be dispatched");
        }

        if (stockStrategy.canDeliveryNoteDeductStock()) {
            for (DeliveryNoteItem item : dn.getItems()) {

                BigDecimal available = warehouseStockService.getAvailableStock(
                        dn.getWarehouse().getId(),
                        item.getProduct().getId());

                int qty = item.getCurrentQty() != null ? item.getCurrentQty() : 0;
                int foc = item.getFoc() != null ? item.getFoc() : 0;
                BigDecimal requested = BigDecimal.valueOf((long) qty + foc);

                if (available.compareTo(requested) < 0) {
                    throw new IllegalStateException(
                            "Insufficient stock for " + item.getProduct().getCode() +
                                    " | Available: " + available +
                                    " | Requested: " + requested);
                }
            }
        }

        dn.setStatus(DeliveryNoteStatus.DISPATCHED);
        DeliveryNote saved = repo.save(dn);

        // Update linked Sales Order status to release SO-level reservation.
        // SI-sourced DNs have no SO — skip this step for them.
        if (dn.getSalesOrderNo() != null && !dn.getSalesOrderNo().isBlank()) {
            salesOrderService.updateStatus(
                    dn.getSalesOrderNo(),
                    com.billbull.backend.sales.salesorder.SalesOrderStatus.DISPATCHED);
        }

        return toResponse(saved);
    }

    @Transactional(rollbackFor = Exception.class, isolation = Isolation.READ_COMMITTED)
    public DeliveryNoteResponse markDelivered(Long id, String receivedBy) {

        DeliveryNote dn = getEntity(id);

        if (dn.getStatus() != DeliveryNoteStatus.DISPATCHED) {
            throw new IllegalStateException("Only Dispatched notes can be delivered");
        }

        // FIX 3 — Idempotency guard: if GL journals already posted for this DN,
        // skip the accounting block entirely to prevent duplicate entries.
        // (Safe to re-enter for status/stock updates since stock duplication guard
        // is handled separately by StockMovementService.)
        if (dn.isFinancialPosted()) {
            dn.setStatus(DeliveryNoteStatus.DELIVERED);
            dn.setReceivedBy(receivedBy);
            dn.setReceivedDate(LocalDate.now());
            if (dn.getSalesOrderNo() != null && !dn.getSalesOrderNo().isBlank()) {
                salesOrderService.updateDeliveredQuantities(dn.getSalesOrderNo(), dn.getItems());
            }
            return toResponse(repo.save(dn));
        }

        if (stockStrategy.canDeliveryNoteDeductStock()) {
            for (DeliveryNoteItem item : dn.getItems()) {

                int qty = item.getCurrentQty() != null ? item.getCurrentQty() : 0;
                int foc = item.getFoc() != null ? item.getFoc() : 0;
                BigDecimal requested = BigDecimal.valueOf((long) qty + foc);

                // HARD VALIDATION WITH RECORD LOCK: check exact physical stock before deducting
                BigDecimal physicalAvailable = stockMovementService.getAvailableStockForUpdate(
                        dn.getWarehouse().getId(),
                        item.getProduct().getId());

                if (physicalAvailable.compareTo(requested) < 0) {
                    throw new IllegalStateException(
                            "Concurrency/Stock Error: Insufficient physical stock for " + item.getProduct().getCode() +
                                    " | Available: " + physicalAvailable +
                                    " | Requested: " + requested);
                }

                Long binId = item.getBinId();

                // AUTO-RESOLVE BIN: if the DN item has no bin, pick the bin with the most
                // stock for this product so the outbound movement is recorded at bin level.
                // Without this, outbound movements land with binId=null and the warehouse
                // bin page shows inflated on-hand that never decreases on sales.
                if (binId == null) {
                    List<Object[]> activeBins = stockMovementRepo.findActiveBinsByWarehouseAndProduct(
                            dn.getWarehouse().getId(), item.getProduct().getId());
                    if (!activeBins.isEmpty()) {
                        binId = (Long) activeBins.get(0)[0]; // bin with highest stock first
                    }
                }

                Long zoneId = null;
                Long locatorId = null;

                if (binId != null) {
                    Bin bin = binRepo.findById(binId).orElse(null);
                    if (bin != null) {
                        locatorId = bin.getLocator() != null ? bin.getLocator().getId() : null;
                        zoneId = (bin.getLocator() != null && bin.getLocator().getZone() != null)
                                ? bin.getLocator().getZone().getId()
                                : null;
                    }
                }

                stockMovementService.postOutboundStock(
                        StockSourceType.DELIVERY_NOTE,
                        dn.getId(),
                        item.getProduct().getId(),
                        dn.getWarehouse().getId(),
                        binId,
                        zoneId,
                        locatorId,
                        qty + foc,
                        dn.getDnNumber());
            }
        }

        dn.setStatus(DeliveryNoteStatus.DELIVERED);
        dn.setReceivedBy(receivedBy);
        dn.setReceivedDate(LocalDate.now());

        // Update linked Sales Order delivered quantities.
        // SI-sourced DNs have no SO — skip this step for them.
        if (dn.getSalesOrderNo() != null && !dn.getSalesOrderNo().isBlank()) {
            salesOrderService.updateDeliveredQuantities(dn.getSalesOrderNo(), dn.getItems());
        }

        // REVENUE + COGS RECOGNITION (IFRS 15 — FIX 1: unified approach)
        // Only runs if this DN is already linked to an invoice.
        // For Before-Sale DNs not yet linked to an invoice: recognition is deferred
        // and triggered by linkDeliveryNotesToInvoice() when the invoice is later raised.
        SalesInvoice invoice = dn.getLinkedSalesInvoice();
        if (invoice != null) {
            Hibernate.initialize(invoice.getItems());
            recognizeRevenueForDeliveredDn(dn, invoice);
        }

        return toResponse(repo.save(dn));
    }

    public DeliveryNoteResponse advanceStatus(Long id, String receivedBy) {
        DeliveryNote dn = getEntity(id);
        if (dn.getStatus() == DeliveryNoteStatus.DRAFT) {
            return markDispatched(id);
        } else if (dn.getStatus() == DeliveryNoteStatus.DISPATCHED) {
            return markDelivered(id, receivedBy);
        } else {
            throw new IllegalStateException("Note is already delivered, cancelled, or in an invalid state");
        }
    }

    @Transactional(rollbackFor = Exception.class)
    public DeliveryNoteResponse cancel(Long id) {
        DeliveryNote dn = getEntity(id);

        // If DELIVERED, reverse stock movements AND accounting journals
        if (dn.getStatus() == DeliveryNoteStatus.DELIVERED) {
            if (stockStrategy.canDeliveryNoteDeductStock()) {
                for (DeliveryNoteItem item : dn.getItems()) {
                    int qty = item.getCurrentQty() != null ? item.getCurrentQty() : 0;
                    int foc = item.getFoc() != null ? item.getFoc() : 0;

                    Long binId = item.getBinId();
                    Long zoneId = null;
                    Long locatorId = null;

                    if (binId != null) {
                        Bin bin = binRepo.findById(binId).orElse(null);
                        if (bin != null) {
                            locatorId = bin.getLocator() != null ? bin.getLocator().getId() : null;
                            zoneId = (bin.getLocator() != null && bin.getLocator().getZone() != null)
                                    ? bin.getLocator().getZone().getId()
                                    : null;
                        }
                    }

                    stockMovementService.reverseOutboundStock(
                            StockSourceType.DELIVERY_NOTE,
                            dn.getId(),
                            item.getProduct().getId(),
                            dn.getWarehouse().getId(),
                            binId,
                            zoneId,
                            locatorId,
                            qty + foc,
                            dn.getDnNumber() + "-REV");
                }
            }

            // FIX 3 + FIX 4 — Only reverse accounting if it was actually posted.
            // Use stored DN amounts directly (not recalculated) to prevent rounding mismatch.
            if (dn.isFinancialPosted()) {
                BigDecimal recognizedRevenue = dn.getRecognizedRevenue();
                BigDecimal recognizedCogs = dn.getRecognizedCogs();

                if ((recognizedRevenue != null && recognizedRevenue.compareTo(BigDecimal.ZERO) > 0)
                        || (recognizedCogs != null && recognizedCogs.compareTo(BigDecimal.ZERO) > 0)) {

                    postingEngineService.reverseJournalFromDeliveryNoteCancellation(
                            dn.getDnNumber(),
                            LocalDate.now(),
                            recognizedRevenue != null ? recognizedRevenue : BigDecimal.ZERO,
                            recognizedCogs != null ? recognizedCogs : BigDecimal.ZERO);

                    // FIX 4 — Subtract the DN's recognized amounts from invoice items
                    // using stored DN totals distributed proportionally by qty.
                    // This is exact even when rounding snap was applied on the final delivery.
                    SalesInvoice invoice = dn.getLinkedSalesInvoice();
                    if (invoice != null) {
                        Hibernate.initialize(invoice.getItems());
                        resetInvoiceItemRecognition(dn, invoice);
                        invoice.setDeliveryStatus(com.billbull.backend.sales.invoice.DeliveryStatus.PENDING);
                    }
                }

                dn.setFinancialPosted(false);
                dn.setRecognizedRevenue(BigDecimal.ZERO);
                dn.setRecognizedCogs(BigDecimal.ZERO);
            }
        }

        dn.setStatus(DeliveryNoteStatus.CANCELLED);

        // Revert Sales Order status to release reservation back to SO level
        if (dn.getSalesOrderNo() != null && !dn.getSalesOrderNo().isBlank()) {
            salesOrderService.updateStatus(
                    dn.getSalesOrderNo(),
                    com.billbull.backend.sales.salesorder.SalesOrderStatus.CONFIRMED);
        }

        return toResponse(repo.save(dn));
    }

    /* ================= INTERNAL ================= */

    /**
     * FIX 1 — Unified revenue + COGS recognition entry point.
     *
     * Called from markDelivered() when the DN already has a linked invoice, and
     * from linkDeliveryNotesToInvoice() for Before-Sale DNs that were delivered
     * before the invoice was raised.
     *
     * Mutates: dn (recognizedRevenue, recognizedCogs, financialPosted)
     *          invoice.items (accumulates recognizedRevenue, recognizedCogs)
     *          invoice (deliveryStatus = DELIVERED on final delivery)
     *
     * Idempotent: returns immediately if financialPosted is already true.
     */
    private void recognizeRevenueForDeliveredDn(DeliveryNote dn, SalesInvoice invoice) {
        if (dn.isFinancialPosted()) return;

        BigDecimal totalRecognizedRevenue = BigDecimal.ZERO;
        BigDecimal totalCogs = BigDecimal.ZERO;

        for (DeliveryNoteItem dnItem : dn.getItems()) {
            int deliveredQty = (dnItem.getCurrentQty() != null ? dnItem.getCurrentQty() : 0)
                    + (dnItem.getFoc() != null ? dnItem.getFoc() : 0);
            if (deliveredQty <= 0) continue;

            // FIX 2 — Cost source: try weighted average from stock ledger first,
            // fall back to product pricing cost. Reject if neither is available.
            Product product = dnItem.getProduct();
            BigDecimal fallbackCost = (product.getPricing() != null)
                    ? product.getPricing().getCost() : null;
            BigDecimal productCost = stockMovementService.getCostForOutbound(
                    product.getId(), dn.getWarehouse().getId(), fallbackCost);

            if (productCost == null || productCost.compareTo(BigDecimal.ZERO) <= 0) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                        "No cost available for '" + dnItem.getItemCode() + "'. "
                                + "Set cost in Product Pricing or ensure inbound stock movements have unit cost.");
            }
            BigDecimal itemCogs = productCost.multiply(BigDecimal.valueOf(deliveredQty));
            totalCogs = totalCogs.add(itemCogs);

            // Match DN item to invoice item by itemCode for proportional revenue
            SalesInvoiceItem matchedInvoiceItem = invoice.getItems().stream()
                    .filter(si -> si.getItemCode() != null
                            && si.getItemCode().equals(dnItem.getItemCode()))
                    .findFirst()
                    .orElse(null);

            if (matchedInvoiceItem != null) {
                int totalInvoiceQty = (matchedInvoiceItem.getQuantity() != null
                        ? matchedInvoiceItem.getQuantity() : 0)
                        + (matchedInvoiceItem.getFoc() != null ? matchedInvoiceItem.getFoc() : 0);

                BigDecimal netAmount = matchedInvoiceItem.getNetAmount() != null
                        ? BigDecimal.valueOf(matchedInvoiceItem.getNetAmount()) : BigDecimal.ZERO;

                BigDecimal proportionalRevenue = totalInvoiceQty > 0
                        ? netAmount.multiply(BigDecimal.valueOf(deliveredQty))
                                .divide(BigDecimal.valueOf(totalInvoiceQty), 2,
                                        java.math.RoundingMode.HALF_UP)
                        : BigDecimal.ZERO;

                // Cap at remaining unrecognized amount to prevent over-recognition
                BigDecimal maxAllowed = netAmount.subtract(matchedInvoiceItem.getRecognizedRevenue());
                if (proportionalRevenue.compareTo(maxAllowed) > 0) {
                    proportionalRevenue = maxAllowed;
                }

                if (proportionalRevenue.compareTo(BigDecimal.ZERO) > 0) {
                    totalRecognizedRevenue = totalRecognizedRevenue.add(proportionalRevenue);
                    matchedInvoiceItem.setRecognizedRevenue(
                            matchedInvoiceItem.getRecognizedRevenue().add(proportionalRevenue));
                    matchedInvoiceItem.setRecognizedCogs(
                            matchedInvoiceItem.getRecognizedCogs().add(itemCogs));
                }
            }
        }

        // Snap any remaining rounding difference on the final delivery
        boolean isFinalDelivery = invoice.getItems().stream()
                .allMatch(si -> {
                    BigDecimal net = si.getNetAmount() != null
                            ? BigDecimal.valueOf(si.getNetAmount()) : BigDecimal.ZERO;
                    return si.getRecognizedRevenue().compareTo(net) >= 0;
                });
        if (isFinalDelivery) {
            BigDecimal totalInvoiceSubTotal = invoice.getSubTotal() != null
                    ? BigDecimal.valueOf(invoice.getSubTotal()) : BigDecimal.ZERO;
            BigDecimal totalAlreadyRecognized = invoice.getItems().stream()
                    .map(SalesInvoiceItem::getRecognizedRevenue)
                    .reduce(BigDecimal.ZERO, BigDecimal::add);
            BigDecimal rounding = totalInvoiceSubTotal.subtract(totalAlreadyRecognized);
            if (rounding.abs().compareTo(BigDecimal.valueOf(0.10)) <= 0
                    && rounding.compareTo(BigDecimal.ZERO) != 0) {
                totalRecognizedRevenue = totalRecognizedRevenue.add(rounding);
            }
            invoice.setDeliveryStatus(com.billbull.backend.sales.invoice.DeliveryStatus.DELIVERED);
        }

        // Store what was recognized for this DN (used by cancellation reversal — Fix 4)
        dn.setRecognizedRevenue(totalRecognizedRevenue);
        dn.setRecognizedCogs(totalCogs);

        // Post journals: Dr Deferred Revenue / Cr Revenue + Dr COGS / Cr Inventory
        if (totalRecognizedRevenue.compareTo(BigDecimal.ZERO) > 0
                || totalCogs.compareTo(BigDecimal.ZERO) > 0) {
            LocalDate journalDate = dn.getReceivedDate() != null ? dn.getReceivedDate()
                    : (dn.getDnDate() != null ? dn.getDnDate() : LocalDate.now());
            postingEngineService.createJournalFromDeliveryNoteDelivered(
                    "DN-" + dn.getDnNumber(),
                    journalDate,
                    dn.getDnNumber(),
                    totalRecognizedRevenue,
                    totalCogs);
        }

        // FIX 3 — Mark as financially posted to prevent duplicate journals on retry
        dn.setFinancialPosted(true);
    }

    /**
     * FIX 4 — Resets invoice item recognized amounts when a delivered DN is cancelled.
     *
     * Uses the stored DN totals (dn.recognizedRevenue / dn.recognizedCogs) distributed
     * proportionally by DN item qty rather than recalculating from invoice netAmount.
     * This ensures the subtracted amounts exactly match what was originally posted,
     * even when a rounding snap was applied on the final delivery.
     */
    private void resetInvoiceItemRecognition(DeliveryNote dn, SalesInvoice invoice) {
        BigDecimal storedRevenue = dn.getRecognizedRevenue() != null
                ? dn.getRecognizedRevenue() : BigDecimal.ZERO;
        BigDecimal storedCogs = dn.getRecognizedCogs() != null
                ? dn.getRecognizedCogs() : BigDecimal.ZERO;

        int totalDnQty = dn.getItems().stream()
                .mapToInt(i -> (i.getCurrentQty() != null ? i.getCurrentQty() : 0)
                        + (i.getFoc() != null ? i.getFoc() : 0))
                .sum();
        if (totalDnQty == 0) return;

        for (DeliveryNoteItem dnItem : dn.getItems()) {
            int dnItemQty = (dnItem.getCurrentQty() != null ? dnItem.getCurrentQty() : 0)
                    + (dnItem.getFoc() != null ? dnItem.getFoc() : 0);
            if (dnItemQty <= 0) continue;

            BigDecimal qtyRatio = BigDecimal.valueOf(dnItemQty)
                    .divide(BigDecimal.valueOf(totalDnQty), 6, java.math.RoundingMode.HALF_UP);
            BigDecimal revenueShare = storedRevenue.multiply(qtyRatio)
                    .setScale(2, java.math.RoundingMode.HALF_UP);
            BigDecimal cogsShare = storedCogs.multiply(qtyRatio)
                    .setScale(2, java.math.RoundingMode.HALF_UP);

            final String itemCode = dnItem.getItemCode();
            invoice.getItems().stream()
                    .filter(si -> itemCode != null && itemCode.equals(si.getItemCode()))
                    .findFirst()
                    .ifPresent(si -> {
                        si.setRecognizedRevenue(
                                si.getRecognizedRevenue().subtract(revenueShare).max(BigDecimal.ZERO));
                        si.setRecognizedCogs(
                                si.getRecognizedCogs().subtract(cogsShare).max(BigDecimal.ZERO));
                    });
        }
    }

    private void hydrateDeliveryItemDisplayData(DeliveryNote dn) {
        if (dn == null || dn.getItems() == null) {
            return;
        }

        dn.getItems().forEach(this::hydrateDeliveryItemDisplayData);
    }

    private void hydrateDeliveryItemDisplayData(DeliveryNoteItem item) {
        if (item == null) {
            return;
        }

        Product product = item.getProduct();
        if (product == null && item.getItemCode() != null && !item.getItemCode().isBlank()) {
            product = productRepo.findByCodeAndIsActiveTrue(item.getItemCode()).orElse(null);
        }

        if (product == null) {
            return;
        }

        if (item.getBarcode() == null || item.getBarcode().isBlank()) {
            String barcode = barcodeRepo.findByProductId(product.getId()).stream()
                    .map(ProductBarcode::getBarcode)
                    .filter(code -> code != null && !code.isBlank())
                    .findFirst()
                    .orElse(null);

            if (barcode != null) {
                item.setBarcode(barcode);
            }
        }

        if (item.getFocUnit() == null || item.getFocUnit().isBlank()) {
            item.setFocUnit(item.getUnit());
        }

        if (item.getRemarks() == null || item.getRemarks().isBlank()) {
            item.setRemarks(item.getDescription());
        }

        // Populate price/cost from product pricing when not stored on the item
        // (covers DNs created before price fields were added to the schema)
        if (item.getPrice() == null && product.getPricing() != null) {
            java.math.BigDecimal retail = product.getPricing().getRetailPrice();
            if (retail != null) {
                item.setPrice(retail.doubleValue());
            }
        }

        if (item.getCost() == null && product.getPricing() != null) {
            java.math.BigDecimal cost = product.getPricing().getCost();
            if (cost != null) {
                item.setCost(cost.doubleValue());
            }
        }
    }

    public DeliveryNote getEntity(Long id) {
        return repo.findById(id)
                .orElseThrow(() -> new RuntimeException("Delivery Note not found"));
    }

    private void mapToEntity(DeliveryNoteRequest req, DeliveryNote dn) {

        Warehouse warehouse = warehouseRepo.findById(req.warehouseId)
                .orElseThrow(() -> new RuntimeException("Warehouse not found"));

        dn.setDnNumber(req.dnNumber);
        dn.setDnDate(req.dnDate);
        dn.setCustomerCode(req.customerCode);
        dn.setCustomerName(req.customerName);
        dn.setSalesOrderNo(req.salesOrderNo);
        dn.setProformaNo(req.proformaNo);
        dn.setWarehouse(warehouse);
        dn.setDriverName(req.driverName);
        dn.setVehicleNo(req.vehicleNo);
        dn.setTrackingNo(req.trackingNo);
        dn.setShippingAddress(req.shippingAddress);

        dn.setAutoGenerated(req.autoGenerated != null ? req.autoGenerated : false);

        // Resolve linked Sales Invoice when the DN is created against a Sales Invoice.
        if (req.linkedSalesInvoiceNumber != null && !req.linkedSalesInvoiceNumber.isBlank()) {
            SalesInvoice invoice = salesInvoiceRepo.findByInvoiceNumber(req.linkedSalesInvoiceNumber)
                    .orElseThrow(() -> new RuntimeException(
                            "Sales Invoice not found: " + req.linkedSalesInvoiceNumber));
            dn.setLinkedSalesInvoice(invoice);
            // Mark source document so stock/status logic can identify SI-sourced DNs.
            dn.setSourceDocumentType("SALES_INVOICE");
            dn.setSourceDocumentId(invoice.getId());
        } else {
            // Preserve any explicitly supplied source document fields (auto-gen paths).
            dn.setSourceDocumentType(req.sourceDocumentType);
            dn.setSourceDocumentId(req.sourceDocumentId);
        }

        int qty = 0;
        int boxes = 0;

        for (DeliveryNoteItemRequest i : req.items) {

            Product product = productRepo.findByCodeAndIsActiveTrue(i.itemCode)
                    .orElseThrow(() -> new RuntimeException("Product not found: " + i.itemCode));

            DeliveryNoteItem item = new DeliveryNoteItem();
            item.setDeliveryNote(dn);
            item.setProduct(product);
            item.setItemCode(i.itemCode);
            item.setBarcode(i.barcode);
            item.setDescription(i.description);
            item.setUnit(i.unit);
            item.setOrderedQty(i.orderedQty);
            item.setPrevDeliveredQty(i.prevDeliveredQty);
            item.setFoc(i.foc);
            item.setFocUnit(i.focUnit);
            item.setRemarks(i.remarks);
            item.setCurrentQty(i.currentQty);
            item.setBoxes(i.boxes);
            item.setImage(i.image);
            item.setBinId(i.binId);
            item.setSalesOrderItemId(i.salesOrderItemId);
            item.setPrice(i.price);
            item.setDisc(i.disc);
            item.setTax(i.tax);
            item.setCost(i.cost);
            hydrateDeliveryItemDisplayData(item);

            dn.getItems().add(item);

            qty += i.currentQty != null ? i.currentQty : 0;
            boxes += i.boxes != null ? i.boxes : 0;
        }

        dn.setTotalLines(dn.getItems().size());
        dn.setTotalQty(qty);
        dn.setTotalBoxes(boxes);
    }

    /**
     * FIX 1 — Links Before-Sale DNs to an invoice and triggers revenue recognition
     * for any DN that is already in DELIVERED status.
     *
     * Before-Sale flow:
     *   1. DN created + delivered (stock deducted) before invoice exists
     *      → at delivery time dn.linkedSalesInvoice is null → no revenue recognition
     *   2. Invoice raised → save() calls this method
     *      → links DN to invoice → DN is DELIVERED + not financially posted
     *      → revenue + COGS recognized here via recognizeRevenueForDeliveredDn()
     */
    @Transactional
    public void linkDeliveryNotesToInvoice(List<String> dnNumbers,
            com.billbull.backend.sales.invoice.SalesInvoice invoice) {
        List<DeliveryNote> notes = repo.findByDnNumberIn(dnNumbers);
        for (DeliveryNote note : notes) {
            note.setLinkedSalesInvoice(invoice);
            repo.save(note);

            // Before-Sale flow: DN already delivered before invoice was raised.
            // Trigger revenue + COGS recognition now that the link is established.
            if (note.getStatus() == DeliveryNoteStatus.DELIVERED && !note.isFinancialPosted()) {
                Hibernate.initialize(note.getItems());
                Hibernate.initialize(invoice.getItems());
                recognizeRevenueForDeliveredDn(note, invoice);
                repo.save(note); // persist financialPosted=true and recognized amounts
            }
        }
    }

    /**
     * Links a single auto-generated Delivery Note to its parent Sales Invoice.
     * Called from SalesInvoiceService within the same transaction to ensure
     * the FK is persisted immediately.
     */
    @Transactional
    public void linkSingleDeliveryNoteToInvoice(Long dnId,
            com.billbull.backend.sales.invoice.SalesInvoice invoice) {
        DeliveryNote dn = getEntity(dnId);
        dn.setLinkedSalesInvoice(invoice);
        repo.save(dn);
    }

    public boolean existsByDnNumber(String dnNumber) {
        return repo.existsByDnNumber(dnNumber);
    }

    @Transactional(readOnly = true)
    public boolean hasActiveDeliveryNoteForSource(String type, Long id) {
        List<DeliveryNote> notes = repo.findBySourceDocumentTypeAndSourceDocumentId(type, id);
        for (DeliveryNote note : notes) {
            if (note.getStatus() != DeliveryNoteStatus.CANCELLED) {
                return true;
            }
        }
        return false;
    }

    @Transactional
    public void cancelBySourceDocument(String type, Long id) {
        List<DeliveryNote> notes = repo.findBySourceDocumentTypeAndSourceDocumentId(type, id);
        for (DeliveryNote note : notes) {
            cancel(note.getId());
        }
    }

    /**
     * FIX 5 — Returns DELIVERED DNs that are linked to an invoice but have no GL journal.
     * Used by the reconciliation endpoint to detect accounting gaps.
     * Filters: financialPosted=false AND no journal exists for "DN-{dnNumber}".
     * (Belt-and-suspenders: financialPosted covers new records; journal check covers
     * pre-migration DNs where the flag did not exist.)
     */
    @Transactional(readOnly = true)
    public List<java.util.Map<String, Object>> findDeliveredWithoutAccounting() {
        return repo.findByStatusAndFinancialPostedFalse(DeliveryNoteStatus.DELIVERED)
                .stream()
                .filter(dn -> dn.getLinkedSalesInvoice() != null)
                .filter(dn -> !postingEngineService.hasJournalForReference("DN-" + dn.getDnNumber()))
                .map(dn -> {
                    java.util.Map<String, Object> m = new java.util.LinkedHashMap<>();
                    m.put("dnNumber", dn.getDnNumber());
                    m.put("customerName", dn.getCustomerName() != null ? dn.getCustomerName() : "");
                    m.put("dnDate", dn.getDnDate() != null ? dn.getDnDate().toString() : "");
                    m.put("linkedInvoice", dn.getLinkedSalesInvoice().getInvoiceNumber() != null
                            ? dn.getLinkedSalesInvoice().getInvoiceNumber() : "");
                    m.put("issue", "Delivery note DELIVERED but no GL journal found");
                    return m;
                })
                .toList();
    }
}
