package com.billbull.backend.sales.delivery;

import java.time.LocalDate;
import java.util.List;

public class DeliveryNoteRequest {

    public String dnNumber;
    public LocalDate dnDate;

    public String customerCode;
    public String customerName;

    public String salesOrderNo;
    public String proformaNo;

    public Long warehouseId; // ✅ FIXED

    public String driverName;
    public String vehicleNo;
    public String trackingNo;
    public String shippingAddress;

    public Boolean autoGenerated;
    public String sourceDocumentType;
    public Long sourceDocumentId;
    public String linkedSalesInvoiceNumber;

    public List<DeliveryNoteItemRequest> items;
}
