package com.billbull.backend.sales.delivery;

import java.time.LocalDate;
import java.util.List;

public class DeliveryNoteResponse {

    public Long id;
    public String dnNumber;
    public LocalDate dnDate;

    public String customerCode;
    public String customerName;

    public String salesOrderNo;
    public String proformaNo;
    public String warehouse;

    public Integer totalLines;
    public Integer totalQty;
    public Integer totalBoxes;

    public String driverName;
    public String vehicleNo;
    public String trackingNo;
    public String shippingAddress;

    public String receivedBy;
    public LocalDate receivedDate;

    public Boolean autoGenerated;
    public String sourceDocumentType;
    public Long sourceDocumentId;
    public String linkedSalesInvoiceNumber;

    public String type;

    public DeliveryNoteStatus status;

    public List<DeliveryNoteItemResponse> items;
}
