BEGIN;
DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'sales_return_item_batches',
    'sales_return_items',
    'sales_returns',
    'sales_invoice_history_events',
    'sales_invoice_items',
    'delivery_note_batch_consumptions',
    'delivery_note_items',
    'delivery_notes',
    'sales_invoices',
    'proforma_invoice_items',
    'proforma_invoices',
    'sales_order_attachments',
    'sales_order_items',
    'sales_orders',
    'sales_quotation_attachments',
    'sales_quotation_revisions',
    'sales_quotation_items',
    'sales_quotations',
    'advance_applications',
    'sales_payments',
    'sales_receipt_vouchers',
    'pdc_entries',
    'opening_invoice',
    'purchase_return_items',
    'purchase_returns',
    'invoice_landed_costs',
    'invoice_payments',
    'purchase_invoice_item_serials',
    'purchase_invoice_items',
    'payment_vouchers',
    'purchase_invoices',
    'grn_item_serials',
    'grn_items',
    'grns',
    'approval_history',
    'approval_workflow_steps',
    'lpo_items',
    'lpos',
    'vendor_advances',
    'expense_voucher_lines',
    'expense_vouchers',
    'expenses',
    'card_settlements',
    'journal_lines',
    'journal_entries',
    'ledger_entries',
    'gl_account_balances',
    'financial_audit_logs',
    'batch_print_queue',
    'batch_allocation',
    'stock_movements',
    'stock_transfer_items',
    'stock_transfers',
    'stock_take_unit_scans',
    'stock_take_expected_units',
    'stock_take_item_batches',
    'stock_take_items',
    'stock_take_sessions',
    'batch_master',
    'serial_master',
    'inventory_balances',
    'bin_stock',
    'pos_cash_movements',
    'pos_sessions',
    'pos_day_closes',
    'pos_held_sales',
    'pos_layaway_payments',
    'pos_layaway_items',
    'pos_layaways',
    'pos_print_jobs',
    'pos_audit_log',
    'pos_device_event_log',
    'pos_device_health_snapshot',
    'pos_discovered_device',
    'inquiry_followups',
    'inquiry_items',
    'customer_inquiries',
    'message_logs',
    'notifications',
    'bank_statement_lines',
    'bank_statements',
    'reconciliation_sessions',
    'tax_filings',
    'salary_repayment_schedules',
    'salary_advance',
    'salary_payments',
    'audit_logs',
    'user_tasks'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    IF to_regclass(t) IS NOT NULL THEN
      EXECUTE format('DELETE FROM %I', t);
      RAISE NOTICE 'cleared %', t;
    ELSE
      RAISE NOTICE 'skipped % (table does not exist on this DB)', t;
    END IF;
  END LOOP;
END $$;
COMMIT;
