apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: max-uploads-pvc
  namespace: billbull
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
