package com.billbull.backend.sales.quotation;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * One-shot startup fix: Postgres holds a CHECK constraint for the
 * sales_quotations.status enum from when the enum had fewer values
 * (DRAFT/PENDING_APPROVAL/APPROVED/REJECTED/CONVERTED/EXPIRED). Hibernate's
 * ddl-auto=update does not refresh check constraints, so adding INVOICED to
 * the enum without dropping the old constraint causes
 * {@code sales_quotations_status_check} violations when we try to write
 * INVOICED.
 *
 * Runs after Hibernate has finished schema sync — drops the stale constraint
 * if it exists. Hibernate will (re)create it on the next startup with all
 * current enum values.
 */
@Component
@Order(0)
public class QuotationStatusConstraintFixer {

    private static final Logger log = LoggerFactory.getLogger(QuotationStatusConstraintFixer.class);

    private final JdbcTemplate jdbc;

    public QuotationStatusConstraintFixer(DataSource dataSource) {
        this.jdbc = new JdbcTemplate(dataSource);
    }

    @EventListener(ApplicationReadyEvent.class)
    public void dropStaleStatusCheck() {
        try {
            jdbc.execute("ALTER TABLE sales_quotations DROP CONSTRAINT IF EXISTS sales_quotations_status_check");
            log.info("Dropped stale sales_quotations_status_check (will be regenerated by Hibernate with current enum values).");
        } catch (Exception e) {
            log.warn("Could not drop sales_quotations_status_check: {}", e.getMessage());
        }
    }
}
