package com.billbull.backend.sales.stockstrategy;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class StockDeductionStrategyService {

    /**
     * Determines if the Delivery Note is allowed to deduct stock based on the
     * current workflow mode.
     */
    public boolean canDeliveryNoteDeductStock() {
        // According to the new logic, BOTH modes deduct physical stock when the DN is
        // marked DELIVERED.
        return true;
    }

    /**
     * Determines if the Sales Invoice is allowed to deduct physical stock itself.
     */
    public boolean canSalesInvoiceDeductStock() {
        // Neither mode should let the invoice aggressively deduct physical stock.
        return false;
    }

    /**
     * Determines if a Delivery Note should be auto-generated upon Sales Invoice
     * confirmation.
     */
    public boolean shouldAutoGenerateDeliveryNote() {
        // Default to false now that configuration is removed
        return false;
    }
}
