-- V52: Cash Drop / Outs Management — financial-ledger fields on pos_cash_movements.
--
-- pos_cash_movements previously had no Flyway migration at all (table was created by
-- Hibernate ddl-auto=update). This migration both formalizes that base table (guarded,
-- so it is a no-op where the table already exists) and adds the additive columns needed
-- to support void/limited-edit/audit on cash drop/out records without ever mutating or
-- deleting the original financial row. All existing rows default to status = 'ACTIVE'.

CREATE TABLE IF NOT EXISTS pos_cash_movements (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pos_session_id        BIGINT,
    movement_type         VARCHAR(20),
    amount                NUMERIC(15,2),
    description           VARCHAR(500),
    performed_by          VARCHAR(255),
    performed_at          TIMESTAMP,
    reference             VARCHAR(100),
    created_at            TIMESTAMP,
    created_by            VARCHAR(255),
    created_by_user_id    BIGINT,
    updated_at            TIMESTAMP,
    updated_by            VARCHAR(255),
    is_active             BOOLEAN DEFAULT TRUE
);

DO $$
BEGIN
    IF to_regclass('pos_cash_movements') IS NOT NULL THEN

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'status') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'void_reason') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN void_reason VARCHAR(500);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'voided_by') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN voided_by VARCHAR(255);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'voided_at') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN voided_at TIMESTAMP;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'edited_by') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN edited_by VARCHAR(255);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'edited_at') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN edited_at TIMESTAMP;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'edit_count') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN edit_count INTEGER NOT NULL DEFAULT 0;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'original_description') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN original_description VARCHAR(500);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'original_reference') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN original_reference VARCHAR(100);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'business_date') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN business_date DATE;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'pos_cash_movements' AND column_name = 'branch_id') THEN
            ALTER TABLE pos_cash_movements ADD COLUMN branch_id BIGINT;
        END IF;

        -- Backfill business_date/branch_id for pre-existing rows from their session, and
        -- normalize status so historical rows (created before this column existed) read as ACTIVE.
        UPDATE pos_cash_movements m
        SET business_date = s.session_date,
            branch_id = s.branch_id
        FROM pos_sessions s
        WHERE m.pos_session_id = s.id
          AND (m.business_date IS NULL OR m.branch_id IS NULL);

        UPDATE pos_cash_movements SET status = 'ACTIVE' WHERE status IS NULL;

    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pos_cash_movement_branch_date ON pos_cash_movements (branch_id, business_date);
CREATE INDEX IF NOT EXISTS idx_pos_cash_movement_status ON pos_cash_movements (status);
