-- V54: Additive cashier "display name" columns for POS reports (X-Report/Z-Report/Day Close).
--
-- Purpose: reports currently show the raw login username as "Cashier" / "Generated By" /
-- "Closed By". This adds resolved-employee-full-name columns alongside the existing
-- username columns so reports can display "Harikrishnan T Nair" instead of "hari.nair"
-- without touching authentication, session ownership, locking, or audit trails, which
-- continue to rely solely on the untouched username columns.
--
-- Values are captured at write-time (session open/close, X-Report generation, Day Close)
-- via User.getResolvedDisplayName(), so historical reports remain immutable even if an
-- employee's name changes later. All DDL is guarded/idempotent — ALTER ADD COLUMN only
-- when the column is absent. No existing column is altered or dropped.

DO $$
BEGIN
    IF to_regclass('pos_sessions') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pos_sessions' AND column_name = 'opened_by_display_name'
        ) THEN
            ALTER TABLE pos_sessions ADD COLUMN opened_by_display_name VARCHAR(150);
            RAISE NOTICE 'Added opened_by_display_name to pos_sessions';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pos_sessions' AND column_name = 'closed_by_display_name'
        ) THEN
            ALTER TABLE pos_sessions ADD COLUMN closed_by_display_name VARCHAR(150);
            RAISE NOTICE 'Added closed_by_display_name to pos_sessions';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pos_sessions' AND column_name = 'x_report_generated_by_display_name'
        ) THEN
            ALTER TABLE pos_sessions ADD COLUMN x_report_generated_by_display_name VARCHAR(150);
            RAISE NOTICE 'Added x_report_generated_by_display_name to pos_sessions';
        END IF;
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('pos_x_report_snapshots') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pos_x_report_snapshots' AND column_name = 'cashier_display_name'
        ) THEN
            ALTER TABLE pos_x_report_snapshots ADD COLUMN cashier_display_name VARCHAR(150);
            RAISE NOTICE 'Added cashier_display_name to pos_x_report_snapshots';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pos_x_report_snapshots' AND column_name = 'generated_by_display_name'
        ) THEN
            ALTER TABLE pos_x_report_snapshots ADD COLUMN generated_by_display_name VARCHAR(150);
            RAISE NOTICE 'Added generated_by_display_name to pos_x_report_snapshots';
        END IF;
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('pos_day_closes') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pos_day_closes' AND column_name = 'closed_by_display_name'
        ) THEN
            ALTER TABLE pos_day_closes ADD COLUMN closed_by_display_name VARCHAR(150);
            RAISE NOTICE 'Added closed_by_display_name to pos_day_closes';
        END IF;
    END IF;
END $$;
