-- V94 Enum status check-constraint drift fix
-- The sales_orders status check constraint was generated by Hibernate from an older
-- SalesOrderStatus enum: it still lists 'CANCELLED' (since removed) and is missing
-- 'FULLY_PAID' (since added). ddl-auto=update never rewrites check constraints, so
-- settling a Sales Order in full failed with
--   new row for relation "sales_orders" violates check constraint "sales_orders_status_check"
-- Same class of drift as V82 on pos_terminals.
--
-- 'CANCELLED' is kept in the allowed list so legacy rows written before the enum
-- changed still satisfy the constraint.

ALTER TABLE sales_orders DROP CONSTRAINT IF EXISTS sales_orders_status_check;

ALTER TABLE sales_orders ADD CONSTRAINT sales_orders_status_check CHECK (
    status::text = ANY (ARRAY[
        'DRAFT'::text,
        'CONFIRMED'::text,
        'PARTIALLY_PAID'::text,
        'FULLY_PAID'::text,
        'PARTIALLY_DELIVERED'::text,
        'INVOICED'::text,
        'DELIVERED'::text,
        'DISPATCHED'::text,
        'CANCELLED'::text
    ])
);

-- Same drift on sales_payments: PaymentStatus gained 'FAILED' (card terminal declined /
-- network error) after the constraint was generated, so recording a failed card payment
-- would fail the identical way.

ALTER TABLE sales_payments DROP CONSTRAINT IF EXISTS sales_payments_status_check;

ALTER TABLE sales_payments ADD CONSTRAINT sales_payments_status_check CHECK (
    status::text = ANY (ARRAY[
        'PENDING'::text,
        'COMPLETED'::text,
        'PARTIAL'::text,
        'CANCELLED'::text,
        'FAILED'::text
    ])
);
